# Generated by Django 3.1.5 on 2021-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='image',
            field=models.ImageField(upload_to='idea_image/%Y/%m/%d/'),
        ),
    ]
